spring:
  application:
    name: JWT-SERVICE
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/LogsDb
    username: root
    password: root
  jpa:
    hibernate.dll-auto: update
    generate-ddl: true
    show-sql: true
  main:
    allow-circular-references: true

server:
  address: 10.0.61.217
  port: 8088


eureka:
  client:
    prefer-same-zone-eureka: false
    serviceUrl:
      defaultZone: http://Abhishek:Baghel@10.0.61.217:8761/eureka/
  instance:
    prefer-Ip-Address: true
    instance-id: ${server.address}:${spring.application.name}:${server.port}




